import path from "node:path";
import { Brain } from "./brain.js";

export function renderBrainMarkdown(brain: Brain): string {
  const lines: string[] = [];
  const p = (s: string) => lines.push(s);

  p("# Project Brain");
  p("");
  p(`> Generated by **Unity Vibe OS** at ${new Date(brain.generatedAt).toISOString()}.`);
  p("> This file is the source of truth for cross-session project understanding.");
  p("> Re-run `uvibe brain` to refresh.");
  p("");
  p("## Identity");
  p("");
  p(`- **Project name**: ${brain.identity.productName ?? "(unknown)"}`);
  p(`- **Company**: ${brain.identity.companyName ?? "(unknown)"}`);
  p(`- **Bundle id**: ${brain.identity.bundleIdentifier ?? "(unknown)"}`);
  p(`- **Project path**: \`${brain.identity.projectPath}\``);
  p(`- **Is Unity project**: ${brain.identity.isUnityProject}`);
  p("");
  p("## Engine");
  p("");
  p(`- **Unity version**: ${brain.engine.unityVersion ?? "(unknown)"}`);
  p(`- **Render pipeline**: ${brain.engine.renderPipeline ?? "(unknown)"}`);
  p(`- **Input system**: ${brain.engine.inputSystem ?? "(unknown)"}`);
  p(`- **Scripting backend**: ${brain.engine.scriptingBackend ?? "(unknown)"}`);
  p(`- **Active build target**: ${brain.engine.defaultBuildTarget ?? "(unknown)"}`);
  p("");
  p(`## Packages (${brain.engine.packages?.length ?? 0})`);
  p("");
  if (brain.engine.packages?.length) {
    for (const pkg of brain.engine.packages) {
      p(`- \`${pkg.name}\` @ ${pkg.version}`);
    }
  } else {
    p("_No packages detected (Packages/manifest.json missing or empty)._");
  }
  p("");
  p("## Asset summary");
  p("");
  p(`- Scenes: ${brain.assets.scenes.length}`);
  p(`- Prefabs: ${brain.assets.prefabs.length}`);
  p(`- Scripts: ${brain.assets.scripts.length}`);
  p(`- ScriptableObject assets (heuristic): ${brain.assets.scriptableObjectAssets.length}`);
  p(`- Materials: ${brain.assets.materials.length}`);
  p(`- Textures: ${brain.assets.textures.length}`);
  p(`- Audio: ${brain.assets.audio.length}`);
  p(`- Total scanned: ${brain.assets.totalAssets}`);
  p("");
  if (brain.assets.scenes.length) {
    p("### Scenes");
    p("");
    for (const s of brain.assets.scenes.slice(0, 30)) p(`- \`${s}\``);
    if (brain.assets.scenes.length > 30) p(`- _…${brain.assets.scenes.length - 30} more_`);
    p("");
  }
  if (brain.assets.prefabs.length) {
    p("### Notable prefabs (first 30)");
    p("");
    for (const s of brain.assets.prefabs.slice(0, 30)) p(`- \`${s}\``);
    if (brain.assets.prefabs.length > 30) p(`- _…${brain.assets.prefabs.length - 30} more_`);
    p("");
  }
  p("## Architecture signals");
  p("");
  p(`- MonoBehaviours detected: ${brain.architecture.monoBehaviours}`);
  p(`- Manager-style classes: ${brain.architecture.managers.length}`);
  p(`- Singleton-pattern usages: ${brain.architecture.singletons.length}`);
  p(`- ScriptableObject types: ${brain.architecture.scriptableObjectTypes.length}`);
  p(`- Object pooling detected: ${yesNo(brain.architecture.hasObjectPooling)}`);
  p(`- Save system detected: ${yesNo(brain.architecture.hasSaveSystem)}`);
  p(`- Audio manager detected: ${yesNo(brain.architecture.hasAudioManager)}`);
  p("");
  if (brain.architecture.scriptableObjectTypes.length) {
    p("### ScriptableObject types");
    p("");
    for (const t of brain.architecture.scriptableObjectTypes.slice(0, 30)) p(`- \`${t}\``);
    p("");
  }
  p("## Conventions");
  p("");
  p("See [`.unity-vibe/conventions.md`](./conventions.md).");
  p("");
  p("## Known issues");
  p("");
  p("Maintained in `.unity-vibe/known_issues.md`.");
  p("");
  p("## Recent feature history");
  p("");
  p("Maintained in `.unity-vibe/feature_history.md`.");
  p("");

  return lines.join("\n");
}

export function renderClaudeContextMarkdown(brain: Brain): string {
  const productName = brain.identity.productName ?? path.basename(brain.identity.projectPath);
  const lines: string[] = [];
  const p = (s: string) => lines.push(s);

  p(`# Claude Context: ${productName}`);
  p("");
  p("This file primes Claude Code for productive work in this Unity project. Read it before answering project-specific questions.");
  p("");
  p("## Project");
  p("");
  p(`- ${productName} on Unity ${brain.engine.unityVersion ?? "(unknown)"}, ${brain.engine.renderPipeline ?? "(unknown render pipeline)"}, ${brain.engine.inputSystem ?? "(unknown input system)"}.`);
  p(`- Build target: ${brain.engine.defaultBuildTarget ?? "(unknown)"}.`);
  p(`- Path: \`${brain.identity.projectPath}\`.`);
  p("");
  p("## How to work here");
  p("");
  p("- Prefer the Unity Vibe OS MCP tools (`unity_*`) over reading raw .unity / .prefab YAML.");
  p("- Always check Unity console (`unity_get_console_logs`) and compile state (`unity_wait_for_compile`) after C# changes.");
  p("- Inspect what the user is looking at via `unity_inspect_selected` before assuming structure.");
  p("- Treat write tools as gated by `.unity-vibe/config.json#safetyMode` (default `read_only`). Do not bypass.");
  p("");
  p("## What's here");
  p("");
  p(`- ${brain.assets.scenes.length} scenes, ${brain.assets.prefabs.length} prefabs, ${brain.assets.scripts.length} C# scripts.`);
  p(`- ${brain.architecture.managers.length} manager-style classes; ${brain.architecture.scriptableObjectTypes.length} ScriptableObject types; pooling=${yesNo(brain.architecture.hasObjectPooling)}, save-system=${yesNo(brain.architecture.hasSaveSystem)}, audio-manager=${yesNo(brain.architecture.hasAudioManager)}.`);
  p("");
  if (brain.assets.scenes.length) {
    p("## Scenes");
    p("");
    for (const s of brain.assets.scenes.slice(0, 12)) p(`- \`${s}\``);
    if (brain.assets.scenes.length > 12) p(`- …and ${brain.assets.scenes.length - 12} more`);
    p("");
  }
  if (brain.architecture.scriptableObjectTypes.length) {
    p("## ScriptableObject types");
    p("");
    p(brain.architecture.scriptableObjectTypes.slice(0, 16).map((t) => `\`${t}\``).join(", "));
    p("");
  }
  p("## Conventions");
  p("");
  p("See [`.unity-vibe/conventions.md`](./conventions.md). Defer to anything documented there.");
  p("");
  p("## Source files referenced by this brain");
  p("");
  p("- `.unity-vibe/project_brain.md` — full project brain (markdown)");
  p("- `.unity-vibe/project_brain.json` — same data structured");
  p("- `.unity-vibe/conventions.md` — project conventions");
  p("- `.unity-vibe/config.json` — safety + runtime config");
  p("");
  return lines.join("\n");
}

export const DEFAULT_CONVENTIONS_MD = `# Project Conventions

> Edit this file freely. Unity Vibe OS reads it for project-specific rules and exposes it to Claude.

## Code style
- C# follows Unity defaults (4-space indent, K&R braces).
- Public fields are PascalCase, private fields are _camelCase.
- Avoid \`FindObjectOfType\` in Update/FixedUpdate.

## Scene & prefab rules
- Never edit \`.unity\` / \`.prefab\` YAML by hand. Always go through the Unity Editor or Unity Vibe OS MCP tools.
- Prefer prefab variants over scene-only edits when authoring shared content.
- Manager singletons live in a \`Bootstrap\` scene loaded first.

## Asset organization
- \`Assets/Art\`, \`Assets/Audio\`, \`Assets/Prefabs\`, \`Assets/Scenes\`, \`Assets/Scripts\`, \`Assets/ScriptableObjects\`.
- ScriptableObjects under \`Assets/ScriptableObjects/<Type>/\`.

## Claude-specific rules
- Use \`unity_inspect_selected\` before assuming what is selected.
- Always compile (\`unity_wait_for_compile\`) and review console (\`unity_get_console_logs\`) after C# edits.
- Never run shell commands that mutate the project; use safe write tools (when available).
- Prefer narrow, additive changes. Open scene only when necessary.
`;

function yesNo(b: boolean): string {
  return b ? "yes" : "no";
}
