import path from "node:path";
import type { Brain } from "./brain.js";
import type { KnowledgeBase, KnowledgeEntity, KnowledgeManifest } from "./knowledge.js";

export function renderBrainMarkdown(brain: Brain, manifest?: KnowledgeManifest): string {
  const lines: string[] = [];
  const p = (value = "") => lines.push(value);
  const coverage = manifest?.coverage ?? brain.assets.coverage;

  p("# Project Brain");
  p();
  p(`> Generated by **Unity Vibe OS** at ${new Date(brain.generatedAt).toISOString()}.`);
  p("> Compatibility summary. The canonical, queryable map is in [`knowledge/`](./knowledge/index.md).");
  p();
  p("## Identity and engine");
  p();
  p(`- Project: ${brain.identity.productName ?? "(unknown)"}`);
  p(`- Company: ${brain.identity.companyName ?? "(unknown)"}`);
  p(`- Bundle id: ${brain.identity.bundleIdentifier ?? "(unknown)"} _(static scan; platform selection is heuristic)_`);
  p(`- Project path: \`${brain.identity.projectPath}\``);
  p(`- Unity: ${brain.engine.unityVersion ?? "(unknown)"}`);
  p(`- Render pipeline: ${brain.engine.renderPipeline ?? "(unknown)"} _(inferred from package manifest)_`);
  p(`- Input system: ${brain.engine.inputSystem ?? "(unknown)"} _(inferred from package manifest)_`);
  p(`- Scripting backend: ${brain.engine.scriptingBackend ?? "(unknown)"} _(static heuristic; live editor is authoritative)_`);
  p(`- Build target: ${brain.engine.defaultBuildTarget ?? "(unknown)"} _(static heuristic; live editor is authoritative)_`);
  p();
  p("## Scan coverage");
  p();
  p(`- Status: ${coverage.complete ? "complete" : coverage.truncated ? "truncated" : "incomplete"}`);
  p(`- Files: ${coverage.scanned} scanned / ${coverage.discovered} discovered (explicit cap: ${coverage.cap})`);
  p(`- First-party scripts: ${brain.assets.firstPartyScripts.length}`);
  p(`- Package/vendor scripts: ${brain.assets.packageScripts.length}`);
  p(`- Read/scan errors: ${coverage.errors.length}`);
  if (coverage.truncated) p("- The map does not claim coverage beyond the reported cap.");
  p();
  p("## Packages");
  p();
  if (brain.engine.packages?.length) {
    for (const pkg of brain.engine.packages) p(`- \`${pkg.name}\` @ ${pkg.version}`);
  } else {
    p("_No package dependencies were found in `Packages/manifest.json`._");
  }
  p();
  p("## Assets");
  p();
  p(`- Scenes: ${brain.assets.scenes.length}`);
  p(`- Prefabs: ${brain.assets.prefabs.length}`);
  p(`- Scripts: ${brain.assets.scripts.length}`);
  p(`- ScriptableObject assets by extension: ${brain.assets.scriptableObjectAssets.length}`);
  p(`- Materials: ${brain.assets.materials.length}`);
  p(`- Textures: ${brain.assets.textures.length}`);
  p(`- Audio: ${brain.assets.audio.length}`);
  p();
  appendPathList(lines, "Scenes", brain.assets.scenes, 30);
  appendPathList(lines, "Prefabs", brain.assets.prefabs, 30);
  p("## Architecture signals (heuristic)");
  p();
  p(`- MonoBehaviours detected by text pattern: ${brain.architecture.monoBehaviours}`);
  p(`- Manager-style filenames: ${brain.architecture.managers.length}`);
  p(`- Singleton-pattern text matches: ${brain.architecture.singletons.length}`);
  p(`- ScriptableObject types detected by text pattern: ${brain.architecture.scriptableObjectTypes.length}`);
  p(`- Object-pooling text match: ${yesNo(brain.architecture.hasObjectPooling)}`);
  p(`- Save-system text match: ${yesNo(brain.architecture.hasSaveSystem)}`);
  p(`- Audio-manager text match: ${yesNo(brain.architecture.hasAudioManager)}`);
  p();
  p("## Curated project knowledge");
  p();
  p("- [`conventions.md`](./conventions.md) — user-maintained rules");
  p("- `known_issues.md` — user-maintained issues, when present");
  p("- `feature_history.md` — user-maintained history, when present");
  p();
  return lines.join("\n");
}

export function renderClaudeContextMarkdown(brain: Brain, manifest?: KnowledgeManifest): string {
  const productName = brain.identity.productName ?? path.basename(brain.identity.projectPath);
  const coverage = manifest?.coverage ?? brain.assets.coverage;
  const lines: string[] = [];
  const p = (value = "") => lines.push(value);

  p(`# AI Project Context: ${productName}`);
  p();
  p("Read `.unity-vibe/knowledge/manifest.json` first. Use `entities.jsonl` and `relations.jsonl`, or the project-brain query API, for narrow questions instead of rescanning the project.");
  p();
  p("## Verified static context");
  p();
  p(`- Unity ${brain.engine.unityVersion ?? "(unknown)"}; render pipeline ${brain.engine.renderPipeline ?? "(unknown)"}; input system ${brain.engine.inputSystem ?? "(unknown)"}.`);
  p(`- ${brain.assets.scenes.length} scenes, ${brain.assets.prefabs.length} prefabs, ${brain.assets.firstPartyScripts.length} first-party scripts, ${brain.assets.packageScripts.length} package/vendor scripts.`);
  p(`- Knowledge coverage is ${coverage.complete ? "complete" : coverage.truncated ? "truncated" : "incomplete"}: ${coverage.scanned}/${coverage.discovered} files, cap ${coverage.cap}, ${coverage.errors.length} errors.`);
  p();
  p("C# declarations, bases, members, and references are conservative text-derived facts. Their provenance, evidence, and confidence are stored with each fact/relation; they are not semantic descriptions.");
  p();
  p("## Working rules");
  p();
  p("- Prefer Unity Vibe OS `unity_*` tools over editing serialized `.unity` or `.prefab` YAML.");
  p("- After C# changes, verify compilation and inspect the Unity console.");
  p("- Treat live editor state as authoritative for active target and settings resolved by Unity.");
  p("- Mark the project brain dirty after mutations; refresh it before relying on the map.");
  p("- Update curated notes when a change affects documented conventions, known issues, or feature history.");
  p();
  p("## Knowledge files");
  p();
  p("- `.unity-vibe/knowledge/index.md` — compact architectural map and coverage");
  p("- `.unity-vibe/knowledge/manifest.json` — schema, freshness, fingerprints, and coverage");
  p("- `.unity-vibe/knowledge/entities.jsonl` — project/package/asset/script/type/module facts");
  p("- `.unity-vibe/knowledge/relations.jsonl` — contains/declares/derives/references graph");
  p("- `.unity-vibe/conventions.md` — curated project rules");
  p();
  return lines.join("\n");
}

export function renderKnowledgeIndexMarkdown(brain: KnowledgeBase): string {
  const { manifest, entities, relations } = brain;
  const lines: string[] = [];
  const p = (value = "") => lines.push(value);
  const byKind = groupByKind(entities);
  const relationCounts = new Map<string, number>();
  for (const relation of relations) relationCounts.set(relation.kind, (relationCounts.get(relation.kind) ?? 0) + 1);

  p(`# Project Knowledge Map: ${manifest.project.name}`);
  p();
  p(`> Schema v${manifest.schemaVersion}; generated ${new Date(manifest.generatedAt).toISOString()}. Canonical machine data lives beside this file in JSONL.`);
  p();
  p("## Coverage and freshness");
  p();
  p(`- State: ${manifest.dirty.value ? "dirty" : "clean"}`);
  p(`- Coverage: ${manifest.coverage.complete ? "complete" : manifest.coverage.truncated ? "truncated" : "incomplete"}`);
  p(`- Files: ${manifest.coverage.scanned}/${manifest.coverage.discovered}; cap ${manifest.coverage.cap}`);
  p(`- First-party: ${manifest.coverage.scopes.firstParty.scanned}/${manifest.coverage.scopes.firstParty.discovered} files; ${manifest.coverage.counts.firstPartyScripts} scripts`);
  p(`- Packages/vendor: ${manifest.coverage.scopes.packages.scanned}/${manifest.coverage.scopes.packages.discovered} files; ${manifest.coverage.counts.packageScripts} scripts`);
  p(`- Errors: ${manifest.coverage.errors.length}`);
  if (manifest.coverage.truncated) p("- **Boundary:** facts beyond the explicit scan cap are unknown, not absent.");
  if (manifest.coverage.errors.length) {
    for (const error of manifest.coverage.errors.slice(0, 10)) p(`- Error at \`${error.path}\`: ${singleLine(error.message)}`);
    if (manifest.coverage.errors.length > 10) p(`- …${manifest.coverage.errors.length - 10} more errors in \`manifest.json\``);
  }
  p();
  p("## Graph summary");
  p();
  p(`- Entities: ${entities.length} (${kindSummary(byKind)})`);
  p(`- Relations: ${relations.length} (${[...relationCounts].sort(([a], [b]) => a.localeCompare(b)).map(([kind, count]) => `${kind} ${count}`).join(", ") || "none"})`);
  p();
  appendEntityPaths(lines, "Modules", byKind.get("module") ?? [], 80);
  appendEntityPaths(lines, "Scenes", byKind.get("scene") ?? [], 40);
  appendEntityPaths(lines, "Prefabs", byKind.get("prefab") ?? [], 40);
  appendPackages(lines, byKind.get("package") ?? []);
  appendTypes(lines, byKind.get("type") ?? [], 120);
  p("## Interpretation rules");
  p();
  p("- Every fact records its source path and observation time.");
  p("- `confidence` appears only for heuristic facts; inspect `provenance.evidence` before acting on them.");
  p("- `contains` is structural, `declares` maps files to types, `derives` maps derived to base, and `references` is a conservative lexical type reference.");
  p("- Query with `queryBrain(projectPath, { query, kinds, limit })` for ranked entities plus bounded graph neighbors and evidence.");
  p();
  return lines.join("\n");
}

export const DEFAULT_CONVENTIONS_MD = `# Project Conventions

> Curated file. Add only rules that are true for this project; knowledge refreshes preserve this file.

## Recorded conventions

_No project-specific conventions have been recorded yet._

## Unity Vibe OS workflow

- Prefer Unity MCP tools for scene and prefab inspection or mutation instead of editing serialized YAML.
- Verify compilation and inspect the Unity console after C# changes.
- Keep this file and other curated notes aligned with material architecture changes.
`;

function appendPathList(lines: string[], title: string, values: string[], limit: number): void {
  if (!values.length) return;
  lines.push(`### ${title}`, "");
  for (const value of values.slice(0, limit)) lines.push(`- \`${value}\``);
  if (values.length > limit) lines.push(`- …${values.length - limit} more in the canonical JSONL map`);
  lines.push("");
}

function appendEntityPaths(lines: string[], title: string, entities: KnowledgeEntity[], limit: number): void {
  if (!entities.length) return;
  lines.push(`## ${title}`, "");
  for (const entity of entities.slice(0, limit)) lines.push(`- \`${entity.path ?? entity.name}\``);
  if (entities.length > limit) lines.push(`- …${entities.length - limit} more in \`entities.jsonl\``);
  lines.push("");
}

function appendPackages(lines: string[], entities: KnowledgeEntity[]): void {
  if (!entities.length) return;
  lines.push("## Packages", "");
  for (const entity of entities) {
    const version = entity.facts.find((fact) => fact.key === "version")?.value;
    lines.push(`- \`${entity.name}\`${version ? ` @ ${String(version)}` : ""}`);
  }
  lines.push("");
}

function appendTypes(lines: string[], entities: KnowledgeEntity[], limit: number): void {
  const local = entities.filter((entity) => entity.scope !== "external");
  if (!local.length) return;
  lines.push("## Declared types", "");
  for (const entity of local.slice(0, limit)) {
    const declaration = entity.facts.find((fact) => fact.key === "declarationKind")?.value;
    const bases = entity.facts.find((fact) => fact.key === "baseTypes")?.value;
    const signatures = entity.facts
      .filter((fact) => fact.key === "memberSignature")
      .map((fact) => String(fact.value));
    lines.push(`- \`${entity.name}\` (${String(declaration ?? "type")}) — \`${entity.path ?? "(unknown path)"}\`${Array.isArray(bases) && bases.length ? `; bases: ${bases.join(", ")}` : ""}`);
    if (signatures.length) lines.push(`  - members: ${signatures.slice(0, 8).map((value) => `\`${value}\``).join(", ")}`);
  }
  if (local.length > limit) lines.push(`- …${local.length - limit} more in \`entities.jsonl\``);
  lines.push("");
}

function groupByKind(entities: KnowledgeEntity[]): Map<string, KnowledgeEntity[]> {
  const grouped = new Map<string, KnowledgeEntity[]>();
  for (const entity of entities) {
    const values = grouped.get(entity.kind);
    if (values) values.push(entity);
    else grouped.set(entity.kind, [entity]);
  }
  return grouped;
}

function kindSummary(grouped: Map<string, KnowledgeEntity[]>): string {
  return [...grouped]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([kind, values]) => `${kind} ${values.length}`)
    .join(", ");
}

function singleLine(value: string): string {
  return value.replace(/\s+/g, " ").trim();
}

function yesNo(value: boolean): string {
  return value ? "yes" : "no";
}
